package:
  format-version: "1.0.0"
  name: "pmci_apps_cec173x"
  type: "application"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.14.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.4.6"
